"""
Simulation Models — Multi-Agent Simulation Data Structures

Domain-agnostic models for any type of swarm simulation.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum


class PlatformType(str, Enum):
    """Simulation platform types."""
    TWITTER = "twitter"
    REDDIT = "reddit"
    CUSTOM = "custom"


class SimulationStatus(str, Enum):
    """Simulation lifecycle states."""
    IDLE = "idle"
    STARTING = "starting"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPING = "stopping"
    STOPPED = "stopped"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class TimeConfig:
    """Simulation time configuration."""
    max_rounds: int = 10
    hours_per_round: int = 1
    start_hour: int = 8       # Simulated start time
    
    # Activity patterns by hour (0-23 → activity multiplier 0.0-1.0)
    activity_pattern: Dict[int, float] = field(default_factory=lambda: {
        h: 0.1 if h < 6 else 0.3 if h < 8 else 0.7 if h < 19 else 1.0 if h < 23 else 0.4
        for h in range(24)
    })
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "max_rounds": self.max_rounds,
            "hours_per_round": self.hours_per_round,
            "start_hour": self.start_hour,
            "activity_pattern": self.activity_pattern,
        }


@dataclass
class EventConfig:
    """A scheduled event that occurs during simulation."""
    event_id: str
    name: str
    description: str
    trigger_round: int                  # Which round to trigger
    affected_agent_ids: List[int] = field(default_factory=list)
    content: str = ""                   # Event seed content
    impact_type: str = "information"    # information, action, mood, etc.
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_id": self.event_id,
            "name": self.name,
            "description": self.description,
            "trigger_round": self.trigger_round,
            "affected_agent_ids": self.affected_agent_ids,
            "content": self.content,
            "impact_type": self.impact_type,
            "metadata": self.metadata,
        }


@dataclass
class AgentProfile:
    """
    A simulation agent's complete profile.
    
    Generated by LLM from knowledge graph entities.
    Contains persona, behavior rules, and platform presence.
    """
    agent_id: int
    name: str
    entity_type: str = ""           # From ontology (Person, Organization, etc.)
    
    # Persona
    bio: str = ""
    personality: str = ""           # e.g., "analytical, cautious, data-driven"
    stance: str = ""                # Position on the topic
    expertise: List[str] = field(default_factory=list)
    
    # Behavior parameters
    activity_level: float = 0.5     # 0.0 (passive) to 1.0 (hyperactive)
    influence_score: float = 0.5    # 0.0 (nobody) to 1.0 (opinion leader)
    emotional_volatility: float = 0.3  # How reactive to events
    
    # Platform presence
    platforms: List[str] = field(default_factory=lambda: ["twitter"])
    followers_count: int = 100
    
    # Memory/context
    initial_memories: List[str] = field(default_factory=list)
    
    # Raw OASIS-compatible profile (for adapter)
    raw_profile: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "agent_id": self.agent_id,
            "name": self.name,
            "entity_type": self.entity_type,
            "bio": self.bio,
            "personality": self.personality,
            "stance": self.stance,
            "expertise": self.expertise,
            "activity_level": self.activity_level,
            "influence_score": self.influence_score,
            "emotional_volatility": self.emotional_volatility,
            "platforms": self.platforms,
            "followers_count": self.followers_count,
            "initial_memories": self.initial_memories,
        }


@dataclass
class AgentAction:
    """A single action taken by an agent during simulation."""
    round_num: int
    timestamp: str
    platform: str
    agent_id: int
    agent_name: str
    action_type: str            # CREATE_POST, LIKE_POST, FOLLOW, DO_NOTHING, etc.
    action_args: Dict[str, Any] = field(default_factory=dict)
    result: Optional[str] = None
    success: bool = True
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "round_num": self.round_num,
            "timestamp": self.timestamp,
            "platform": self.platform,
            "agent_id": self.agent_id,
            "agent_name": self.agent_name,
            "action_type": self.action_type,
            "action_args": self.action_args,
            "result": self.result,
            "success": self.success,
        }


@dataclass
class SimulationRound:
    """Summary of a single simulation round."""
    round_num: int
    start_time: str
    end_time: Optional[str] = None
    simulated_hour: int = 0
    actions: List[AgentAction] = field(default_factory=list)
    active_agent_ids: List[int] = field(default_factory=list)
    platform_stats: Dict[str, int] = field(default_factory=dict)  # platform → action count
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "round_num": self.round_num,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "simulated_hour": self.simulated_hour,
            "actions_count": len(self.actions),
            "actions": [a.to_dict() for a in self.actions],
            "active_agent_ids": self.active_agent_ids,
            "platform_stats": self.platform_stats,
        }


@dataclass
class PlatformConfig:
    """Configuration for a simulation platform."""
    platform_type: PlatformType
    enabled: bool = True
    available_actions: List[str] = field(default_factory=list)
    initial_posts: List[Dict[str, Any]] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "platform_type": self.platform_type.value,
            "enabled": self.enabled,
            "available_actions": self.available_actions,
            "initial_posts": self.initial_posts,
        }


@dataclass
class SimulationConfig:
    """
    Complete simulation configuration.
    
    Generated by LLM from requirements + knowledge graph.
    """
    sim_id: str = ""
    requirement: str = ""               # What to predict/simulate
    time_config: TimeConfig = field(default_factory=TimeConfig)
    events: List[EventConfig] = field(default_factory=list)
    platforms: List[PlatformConfig] = field(default_factory=list)
    
    # Domain-specific config (extensible)
    domain_config: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "sim_id": self.sim_id,
            "requirement": self.requirement,
            "time_config": self.time_config.to_dict(),
            "events": [e.to_dict() for e in self.events],
            "platforms": [p.to_dict() for p in self.platforms],
            "domain_config": self.domain_config,
        }


@dataclass
class SimulationState:
    """Runtime state of a simulation."""
    sim_id: str
    status: SimulationStatus = SimulationStatus.IDLE
    current_round: int = 0
    total_rounds: int = 0
    rounds: List[SimulationRound] = field(default_factory=list)
    agents: List[AgentProfile] = field(default_factory=list)
    error_message: Optional[str] = None
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    
    @property
    def total_actions(self) -> int:
        return sum(len(r.actions) for r in self.rounds)
    
    @property
    def progress(self) -> float:
        if self.total_rounds == 0:
            return 0.0
        return self.current_round / self.total_rounds
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "sim_id": self.sim_id,
            "status": self.status.value,
            "current_round": self.current_round,
            "total_rounds": self.total_rounds,
            "total_actions": self.total_actions,
            "progress": self.progress,
            "error_message": self.error_message,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
        }
